version: 2.1
orbs:
  r-packages: displayr/r-packages@dev:alpha
parameters:
  trigger-message:
    type: string
    default: ""
  remote-deps:
    type: string
    default: ""
  plugins-branch:
    type: string
    default: ""
  triggered-packages:
    type: string
    default: ""
  executor:
    type: enum
    enum: [nightly, rocker, machine]
    default: nightly

workflows:
  build-and-check-R-package:
    jobs:
      - r-packages/build-and-check-package:
          executor: << pipeline.parameters.executor >>
          resource-class: large
          name: BuildAndCheckPackage
          context:
            - r_packages
          remote-deps: << pipeline.parameters.remote-deps >>
          separate-test-job: true
      - r-packages/test-package:
          executor: << pipeline.parameters.executor >>
          resource-class: large
          name: TestPackage
          requires:
            - BuildAndCheckPackage
          context:
            - r_packages
